import { Inter } from "next/font/google";
import "./globals.css";

import { Epilogue, DM_Sans, Syne, Manrope } from "next/font/google"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Fontes do Google
const epilogue = Epilogue ({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Tamanho da fonte
  style: ["normal", "italic"], // Estilo
  variable: ["--font-epilogue"], //Definir o nome de variavel
  subsets: ["latin"], // Padrão
  display: "swap",  // Padrão
});

const dmsans = DM_Sans ({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Tamanho da fonte
  style: ["normal", "italic"], // Estilo
  variable: ["--font-dm_sans"], //Definir o nome de variavel
  subsets: ["latin"], // Padrão
  display: "swap",  // Padrão
});

const manrope = Manrope ({
  weight: ["200", "300", "400", "500", "600", "700", "800"], // Tamanho da fonte
  style: ["normal"], // Estilo
  variable: ["--font-manrope"], //Definir o nome de variavel
  subsets: ["latin"], // Padrão
  display: "swap",  // Padrão
});

const syne = Syne ({
  weight: ["400", "500", "600", "700", "800"], // Tamanho da fonte
  style: ["normal"], // Estilo
  variable: ["--font-syne"], //Definir o nome de variavel
  subsets: ["latin"], // Padrão
  display: "swap",  // Padrão
});

//Fontes Local

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${epilogue.variable} ${dmsans.variable} ${syne.variable} ${manrope.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
